### ISSUE TITLE
"Generate a Random Password" does not work

### ISSUE THREAD

**Issue by noahadvs** [belaviyo/keepass-macpass-helper#1]
I am using KDE neon with Plasma 5.9.4
If I right click on the KeePass Helper icon in the toolbar and select "Generate a Random Password", I get a notification saying "Generated password is copied to the clipboard", but nothing is actually copied to the clipboard.

Here is a video of what I'm doing. In the video, I also try setting the password generator back to the default settings, but that does not help.
https://youtu.be/p_SBAhW8nQc

**Comment by belaviyo** [comment]
Can you try it when a normal (not chrome://) page is active. Like over www.google.com. Basically, when extension wants to save the generated password, it uses the current page to perform copy-to-clipboard and I think it is not working on chrome pages.

**Comment by noahadvs** [comment]
I have. My college's login page is where I tried it first and it still didn't work on other pages with text fields.

**Comment by belaviyo** [comment]
Thanks for the report. It should be fixed on the dev version. To confirm please follow

1. Open about:debugging in a browser tab
2. Download and extract https://github.com/belaviyo/keepass-macpass-helper/archive/master.zip
3. Point the "Load Temporary add-on" to `manifest.json`

**Comment by noahadvs** [comment]
It works. Thanks.
