### ISSUE TITLE
non-structured-clonable data notification on some websites

### ISSUE THREAD

**Issue by janteau** [belaviyo/keepass-macpass-helper#15]
I receive a KeePassHelper notification on some websites (sears.com is a good example) when KeePassHelper enters login data.  The notification states: "Script 'moz-extension://f179700f-3e21-45bf-bad4-1d6028751de6/data/dmd/inject.js' result is non-structured-clonable data".

![image](https://user-images.githubusercontent.com/32575346/31284780-8e00d5b2-aa87-11e7-93cd-f3c523d78540.png)

This is on Firefox 55.0.3 with KeePassHelper Password Manager 0.2.9 running on Windows 7 and 10.

**Comment by belaviyo** [comment]
How many logins do you have for sears.com for example? I am not able to reproduce this on FF 55. Do you have anything special in the username or password fields?

**Comment by janteau** [comment]
I only have one login for sears.com and the password is only alphanumeric.  I get the notification even when my database is locked so KeePassHelper is not even getting any login information.  usbank.com is another website that produces this behavior, also with the database locked or unlocked.  I just tried it on my laptop with Firefox 56.0 on Mac OS X 10.11.16 and the same occurs.

**Comment by belaviyo** [comment]
Do you have a legacy addon installed on your Firefox?

**Comment by janteau** [comment]
I did (but they were disabled).  I removed the one I had on my Mac OS X installation and restarted Firefox.  I get the same notification.  KeePasHelper is the only addon in Firefox in the Mac installation.

**Comment by belaviyo** [comment]
Unfortunetly, I am not able to reproduce this. That's a good idea. Please try the extension on a clean profile (http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html)

You can also try it on Google Chrome to see if this bug relates to FF or you can reproduce it even on Chrome

**Comment by janteau** [comment]
I deleted the only profile on my Mac, created a new one, and the only setting change to the browser I made was to add the KeePassHelper extension.  I still got the unexpected notification when clicking the KeePassHelper button on sears.com.  

I added the extension to Chrome, and do not get the unexpected notification on Chrome.  It seems it's a Firefox only bug.

**Comment by belaviyo** [comment]
Please add a dummy login for sears.com in your KeePass application and retry with this new credential. See if you still get that error or not.

**Comment by janteau** [comment]
I created a new KeePass database with the only account sears.com.  The notification still appears with this new database.  The notification appears even when the database is locked or when the KeePass application is closed.

Here is the sample database file:  https://www.dropbox.com/s/5it1n6yu77211la/pwDatabase2.kdbx?dl=0
The password is: password

**Comment by belaviyo** [comment]
Thanks. Got it fixed. I was able to reproduce this on Windows not Mac.

You can give the latest dev version a try and confirm
1. Download the project and extract it into a local directory
https://github.com/belaviyo/keepass-macpass-helper/archive/master.zip
2. Open about:debugging and point the "Install temporary add-on" to the `manifest.json` file located in the root of the extracted folder.

**Comment by janteau** [comment]
Fixes the issue!  

Thanks for the add-on.  It's my favorite of all of them that I've tried.  It's simple, resource light, and does what it's supposed to!

**Comment by janteau** [comment]
I confirmed that it also fixes the issue on my Mac.

Thanks!
