### ISSUE TITLE
Populate String Field

### ISSUE THREAD

**Issue by LtlBear** [belaviyo/keepass-macpass-helper#18]
I have a few websites that I use that require a username, password, plus some other data to be able to log in.  I can store them in KeePass as string fields on the Advanced tab and use Control-V to autopopulate the web site.  However, i prefer to use an extension in Opera to help populate the fields.  I cannot find a way in KeePassHelper to make it populate the proper string fields.  [KeeFox can handle them fine in Firefox and ChromeIPass can be configured to handle them in Chrome].  How do I handle them in KeePassHelper?

**Comment by belaviyo** [comment]
Can you provide a sample website?

**Comment by LtlBear** [comment]
One example is American Airlines - www.aa.com

**Comment by belaviyo** [comment]
Thanks for the report. It is now implemented in the dev version. Please give it a try and let me know if it works as expected or not

1. Download and unzip https://github.com/belaviyo/keepass-macpass-helper/archive/master.zip
2. Drop the root dir to chrome://extensions/

Note that in the KeePassHelper extension the "Key" field is used to match elements within the form as explained in https://add0n.com/keepass-helper.html#faq12

**Comment by LtlBear** [comment]
That works now.  Thanks.

**Comment by janteau** [comment]
@belaviyo:
I have not had luck with this feature working.  Using aa.com as a test website.  I am using Firefox 57 on both Windows (official KeePass) and Mac (KeepassXC).

For the "Last Name" text box on aa.com:

![image](https://user-images.githubusercontent.com/32575346/34074219-603d5ae6-e278-11e7-8d20-63a1351fb538.png)

I have created a key called `KPH: lastName` and have also tried `KPH: loginForm.lastName`:

![image](https://user-images.githubusercontent.com/32575346/34074252-44fc3db4-e279-11e7-872d-b775d8bdcb59.png)


When I click "Both" from the keepasshelper menu, password is inserted into "Last Name" box:

![image](https://user-images.githubusercontent.com/32575346/34074229-cef88226-e278-11e7-84a0-51d2524580ce.png)

I can get it to work with chromeIPass, so I believe KeePassHTTP is passing the string field.

**Comment by belaviyo** [comment]
@janteau KeepassXC was appending `KPH: ` with keys. So the id was wrong. I pushed an update to fix this. Update to 0.3.8 and you could be able to use the KeepassXC for both stringFields and OTP token generation.

I have no idea why your official KeePass application is not working. I just checked KeePassHelper with this website and it works fine for me. Please retry with 0.3.8 and let me know if you still have the issue.

**Comment by janteau** [comment]
@belaviyo This appears to fix for both KeepassXC (Mac) and official KeePass (windows).  I tried on two different websites that I have custom strings defined for.

Interesting issue on aa.com though when using official KeePass on Windows.  When I press "Both", all fields are correctly populated, the form is submitted, but aa.com loops right back to the main screen.  If I enter all the fields one at a time, e.g. press "Username", type Last Name manually, press "Password", and then press Log In it works fine.  It works as expected on my mac with KeepassXC.

**Comment by belaviyo** [comment]
> but aa.com loops right back to the main screen

Try this method:

Open the popup, and instead of pressing the "Both" button, press Alt + B on Windows. This way the form only gets populated. Then press the Enter key to submit. Some websites check user actions and only accept logins when the event is trusted.

**Comment by janteau** [comment]
> Open the popup, and instead of pressing the "Both" button, press Alt + B on Windows.

That's not possible on Firefox.  Alt + B opens the Bookmarks menu.

(I'm sure supporting multiple browsers that don't all act the same is frustrating.)

**Comment by belaviyo** [comment]
> That's not possible on Firefox. Alt + B opens the Bookmarks menu.

Make sure an element in the popup is focused before pressing the keyboard shortcut. Hover your mouse over the "Both" button to see other options. I think Ctrl + B should work too!

**Comment by janteau** [comment]
> Make sure an element in the popup is focused before pressing the keyboard shortcut. Hover your mouse over the "Both" button to see other options. I think Ctrl + B should work too!
You're right!  If I specifically click the element (even though it's already highlighted) it works as intended.

Populating the login fields on aa.com with Alt + B and then clicking Log In results in a successful login.  It's odd that there's different between the same website between Mac and Windows (both FF 57).

**Comment by janteau** [comment]
Let me ask this question about the string populates.  

A "Both" (Alt+B) command on gmail.com results in username being filled in on the first screen, password automatically filled in on password screen (without any button presses), but my custom string for the TOTP on the third page is not auto entered.  Is there a reason the custom strings behave different than the username and password fill-ins?

**Comment by belaviyo** [comment]
> Is there a reason the custom strings behave different than the username and password fill-ins?

The username and password fields are actually located on the same page but Gmail hides the password field when there is no username. The TFA field most likely is not located on this page. Gmail redirects to it if it is enabled. I would say if the field gets focused and The "Both" button is pressed, the {TOTP} will be inserted as well on the second page.

**Comment by janteau** [comment]
Makes sense.  Thanks for the support and development!

**Comment by graphixillusion** [comment]
I'm having the exact same issue. Everything seems correctly configured but still doesn't work. Tried both in Firefox and Chrome.
