### ISSUE TITLE
Does not work on Firefox Sync login page

### ISSUE THREAD

**Issue by noahadvs** [belaviyo/keepass-macpass-helper#2]
This probably has something to do with the addon not working on `chrome://` pages. The address Firefox has in the Awesomebar for the login page is `about:accounts?action=signin&entrypoint=preferences`

When I click on the icon in the toolbar while I'm on that page, it does nothing.

**Comment by belaviyo** [comment]
Right! WebExtension has no access to chrome:// pages and hence there is no way to fix this as far as I know.
