### ISSUE TITLE
Google TOTP issue with "Both" function

### ISSUE THREAD

**Issue by janteau** [belaviyo/keepass-macpass-helper#20]
Seems Google has changed their login page to now allow an automated submit on the TOTP input page.  When I use the "Both" function in keepasshelper to enter my TOTP (which is a KPH custom string) it pastes the OTP and submits, but Google just reloads the page.  If I manually copy the OTP from KeePass and paste it, then click the Google submit button, it logs in as expected.

**Comment by belaviyo** [comment]
Thanks for the report. Please update to 0.4.0 release and reopen if the problem is not fixed.
