### ISSUE TITLE
Bug with inserting both credentials on Mega.nz

### ISSUE THREAD

**Issue by SlavMetal** [belaviyo/keepass-macpass-helper#24]
Hi there! When trying to log in to the Mega.nz account via using the addon's feature of inserting both credentials (username and password) at the same time, only blank page (with those credentials in the address bar) will be opened and log in won't be performed.

Software details:
- Firefox Developer Edition 61.0b10 (previous versions are also affected actually)
- KeePassHelper Password Manager 0.3.9

Steps to reproduce:
1. Open [mega.nz](https://mega.nz/) or [mega.nz/login](https://mega.nz/login).
2. Focus on the username field.
3. Open the KeePassHelper Password Manager and press Both (B) button.

![deepinscreenshot_select-area_20180601135500](https://user-images.githubusercontent.com/17832892/40839953-eb024f92-65a4-11e8-80c1-759dc2eeff96.png)

**Comment by belaviyo** [comment]
Thanks for the report. Please update to 0.4.0 release and reopen if it is not still fixed.
