### ISSUE TITLE
OTP not detected

### ISSUE THREAD

**Issue by Swiiney** [belaviyo/keepass-macpass-helper#30]
I have several sites requesting OTP to connect but I have 2 issues when trying to use it :

- The plugin doesn't detect the field otp : "No string-field entry...". I doubled check and the field otp exists with a string "key=...". 

- I am also using KeeOTP plugin which propose OTP generation in Keepass interface like your Firefox plugin. But for this it is using a "TOTP Seed" field. It would be great if your plugin used the same field (or at least regognise both).

**Comment by high5five** [comment]
Try unchecking "Only return advanced string fields that start with KPH:".
That solved the issue for me.

**Comment by rburgst** [comment]
this option does not seem to exist in macPass
