### ISSUE TITLE
KeePassHelper cannot connect to keepasshttp

### ISSUE THREAD

**Issue by TomTasaky** [belaviyo/keepass-macpass-helper#31]
Hello

Using KeePass earlier on Ubuntu 18.04, I changed it to XC 2.3.1. I installed it on all KeePassHelper browsers. However, there is no connection to the database or the program itself. I have a message everywhere:

can not connect to keepasshttp. either keepass is not running or communication is broken "data-password =" "> can not connect to keepasshttp. either keep is not running or communication is broken

**Comment by belaviyo** [comment]
KeePassXC moved to the native messaging method. There is no support for KeePassHTTP plugin anymore. As of the next release we are going to support the native method too. Go to the options page and follow the instruction.
