### ISSUE TITLE
Can't connect to database "Die Signatur ist falsch."

### ISSUE THREAD

**Issue by Testingtim** [belaviyo/keepass-macpass-helper#37]
Hi,
I just switched to KeePass Helper because suddenly the Kee-Addon didn't worked anymore (Couldn't connect, tried everything).

Unfortunately Keepass Helper also doesn't work but at least it connects to KeePass and gives me a error message.
Could you please tell me whats wrong?

Windows 8.1
KeePass 2.43
KeePassHTTP 1.8.4.2

First time I clicked the Toolbar I had to accept the security dialog.
And now, everytime I click the button I get the following error message:
---------------------------

---------------------------
System.TypeLoadException: Die Signatur ist falsch.

   bei System.Text.RegularExpressions.RegexParser.CountCaptures()

   bei System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)

   bei System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)

   bei System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)

   bei KeePassLib.PwGroup.SearchEntriesSingle(PwObjectList`1 lSource, SearchParameters sp, PwObjectList`1 lResults, IStatusLogger slStatus, UInt64& uPrcEntries, UInt64 uTotalEntries)

   bei KeePassLib.PwGroup.SearchEntries(SearchParameters sp, PwObjectList`1 lResults, IStatusLogger slStatus)

   bei KeePassHttp.KeePassHttpExt.FindMatchingEntries(Request r, Aes aes)

   bei KeePassHttp.KeePassHttpExt.GetLoginsHandler(Request r, Response resp, Aes aes)

   bei KeePassHttp.KeePassHttpExt.ProcessRequest(Request r, HttpListenerResponse resp)
---------------------------
OK   
---------------------------

Please tell me what to do.

Thank you!

**Comment by belaviyo** [comment]
Have you tried to remove the KeePassHTTP plugin and reinstall it?

**Comment by Testingtim** [comment]
yeah for sure, I even reinstalled KeePass completely. There is still no solution. Only thing I didn't tried is to reset my firefox profile, but that's the last thing I want to do.

**Comment by belaviyo** [comment]
I suggest to try with Chrome to see if the issue is from the extension side or the KeePass application side.

**Comment by Testingtim** [comment]
I fixed it!
It was a broken .net installation! I used the .net framework cleanup tool to remove the .net 4.6 and 4.5.2 version. After that everything worked :)
