### ISSUE TITLE
Firefox 70.0.1 can't access anymore to KeePassHTTP

### ISSUE THREAD

**Issue by Magneticdud** [belaviyo/keepass-macpass-helper#38]
Hi, using KeePassHTTP on KeePass for Windows.

This morning I got an update to Firefox, now the plugin can't communicate anymore to KeePass. It might be an issue with Firefox, as ALL the addons in the mozilla marketplace can't communicate with it.

**Comment by belaviyo** [comment]
Go to the options page and click on the "Auto-Login" button. Then restart your browser. Let me know if it works
