### ISSUE TITLE
Sudden change in operation

### ISSUE THREAD

**Issue by katchatour** [belaviyo/keepass-macpass-helper#39]
Windows 10 enterprise 1903 and Firefox 70.0.1
Suddenly Keepasshelper no longer seems to work on Aliexpress registration page only.
When clicking the correctly registered element in Keepass floating window nothing is entered on the Aliexpress page.
This only happens with Aliexpress.

**Comment by belaviyo** [comment]
Go to the options page and click on the "auto-login permission" button. By default, this extension only has the active tab permission which prevents it from accessing cross-origin domains. Seems like Aliexpress is using a cross-origin iframe for its login box. Just allow the extension to access all hostnames and restart your Firefox once. It should fix the issue.

Alternatively, you can only allow the extension to have access to this particular hostname from the "Check" button which is a bit more complex.

**Comment by belaviyo** [comment]
Please reopen if the problem persists after granting the permission and a restart

**Comment by katchatour** [comment]
Thank you!
