### ISSUE TITLE
Support for OTP

### ISSUE THREAD

**Issue by abno85** [belaviyo/keepass-macpass-helper#4]
Are there any plans to support the KeeOTP plugin?
See [here](http://keepass.info/plugins.html#keeotp) and [here](https://bitbucket.org/devinmartin/keeotp/wiki/Home)

Would be great to use your extension for pasting authenticator codes.

Thanks!

**Comment by belaviyo** [comment]
Note that we use KeePassHttp for communication with the KeePass application and hence this plugin needs to be able to communicate with KeeOTP plugin which I doubt.

**Comment by iceman73** [comment]
It Does via this pull Request

https://github.com/pfn/keepasshttp/pull/325

**Comment by belaviyo** [comment]
Please ping when it is merged.

**Comment by janteau** [comment]
I'm a user of TrayTOTP and would also appreciate this feature.

**Comment by rithvikvibhu** [comment]
@belaviyo A heads up, It's merged.

**Comment by belaviyo** [comment]
Okay, so we have TOTP support without the need to have a plugin! Here is how it works:

1. Copy to clipboard:

Define a new string-filed with:
Key: `otp`
Value: `key=OTP_Secret`

2. Automatic insert:
Considering the `otp` string-field is available, you can insert time tokens with `{TOTP}` keyword. Basically, `{TOTP}` keyword is replaced with the current time token in all string values.

To insert a string-filled into a custom field read FAQ 12; https://add0n.com/keepass-helper.html

Please give the latest dev version a try and let me know if it works as expected.

**Comment by janteau** [comment]
I believe having the key value in the form `key=OTP_Secret` is going to cause compatibility issues with current OTP solutions like TrayTOTP and Keepass2Android.  While the key name is definable in both (TrayTOTP and K2A default to TOTP Seed), they use key value as just `OTP_Secret`

I'm a little confused on how custom strings are inserted in keepass-helper.  I'm mostly a user of the separate click buttons form the KeyLock Icon menu.  Most TOTP requests on a page are on a different screen than the User/Pass information.  How do I go about inserting a custom string value in this text box?

**Comment by belaviyo** [comment]
> they use key value as just OTP_Secret

https://keepass.info/plugins.html#keeotp uses this format. The issue with `OTP_Secret` is that there would be no control on other parameters like duration for instance (not that we support this at the moment, but it is important).

> I'm a little confused 

When the "Both" button is pressed and if string fields are available, the extension matches each key with both id and name attributes of the elements inside the form and if a match is detected, the value is inserted. Even if the OTP is located on the second page, just focus the field and press the "Both" button.

Guys, since it is not really secure to have `OTP_Secret` stored in the database, I added support for secure `OTP_Secret`s. Read FAQ13 for more info.

**Comment by janteau** [comment]
TrayTOTP accomplishes the other parameters issue by utilizing a separate key "TOTP Settings".  Maybe supporting both KeeOTP and TrayTOTP is unrealistic or not worth the effort, but both KeepassXC and Keepass2Android seem to support both methods.

![image](https://user-images.githubusercontent.com/32575346/34050514-2d6241f8-e189-11e7-82e2-8969bc1dc008.png)


I will play with the "Both" command further.  I've noticed "Both" causes an issue on the Google login page (username, password, otp all on separate pages).  After hitting "Both" on the username page, the form is submitted, but google loops back and asks for the username again.  I just utilize "Username" and "Password" buttons separately.  If using "Both" for the OTP page works, then that's fine with me.

**Comment by belaviyo** [comment]
@janteau first I do NOT recommend to store the secret directly in the KeePass database. Use the encryption tool and save the `sotp`. 

> TrayTOTP accomplishes the other parameters issue by utilizing a separate key "TOTP Settings"

Based on your image, TrayTOTP requires `TOTP Seed` not the `otp` key. I am not sure why there is a conflict

**Comment by janteau** [comment]
I misunderstood this feature.  I now realize that Keepasshelper is providing OTP support without the use of a third-party plugin in KeePass.  Sorry for the confusion.
