### ISSUE TITLE
Integration with KeePassXC

### ISSUE THREAD

**Issue by piotrek-k** [belaviyo/keepass-macpass-helper#40]
Hi,
I'm trying to setup KeePassHelper to work with KeePassXC. I've installed KeePassHelper on Firefox, enabled browser integration on KeepassXC and modified `org.keepassxc.keepassxc_browser_firefox.json` file as described in "Options" tab of this extension in Firefox. Here is my configuration:

```
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org",
        "69ef9498-0139-43e4-97b8-942982ac9158" <---- added addon ID
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "C:\\Program Files\\KeePassXC\\keepassxc-proxy.exe",
    "type": "stdio"
}
```

I've also changed "Connection" in Firefox Addon Options tab to "Netive Messaging (KeePassXC)"

When I try to fill passwords, addon shows such message:
> "change-public-keys" failed. Does KeePassHelper have access to native application?

**Comment by belaviyo** [comment]
try `"{69ef9498-0139-43e4-97b8-942982ac9158}"`

**Comment by belaviyo** [comment]
I think you need to restart the browser once too.

**Comment by piotrek-k** [comment]
Current state of `C:\Users\[...]\AppData\Local\keepassxc\org.keepassxc.keepassxc_browser_firefox.json`:
```
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org",
        "{69ef9498-0139-43e4-97b8-942982ac9158}"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "C:\\Program Files\\KeePassXC\\keepassxc-proxy.exe",
    "type": "stdio"
}
```
I've also tried restarting browser. Problem still persists.

I'm trying to run this on Windows, Firefox 71.  I've been successfully using another browser extension `KeePassXC-Browser`, so I presume KeePassXC is configured correctly for cooperation with browser.

**Comment by belaviyo** [comment]
Interesting enough you need to modify org.keepassxc.keepassxc_browser_tor-browser.json on Windows!

**Comment by piotrek-k** [comment]
> 
> 
> Interesting enough you need to modify org.keepassxc.keepassxc_browser_tor-browser.json on Windows!

Thank you, it works now. You should definitely make installation instructions more clear.
