### ISSUE TITLE
Can't find credentials when using two databases in MacPass

### ISSUE THREAD

**Issue by odkr** [belaviyo/keepass-macpass-helper#41]
I’m not sure whether this is an issue with KeePass Helper or MacPass, but when I open two password databases, KeePass Helper only offers me credentials from one of the two, not from both.

I’m using KeePass Helper v0.4.5,  Firefox v72.0.1 (64-bit), and MacPass v0.7.10 (22740).

**Comment by belaviyo** [comment]
I am not sure about MacPass, but for KeePass, you need to check "Seach in all opened dbs...". If so the extension displays all the matches

![Screen Shot 2020-03-14 at 1 26 27 PM](https://user-images.githubusercontent.com/1221138/76681924-7d2e5900-65ef-11ea-83f1-94855d22a3b5.png)

**Comment by odkr** [comment]
Oh, sorry, I didn’t notice that you responded back in the day and just stumpled upon this. So it probably *is* an issue with MacPass (which doesn't have such an option). Good to know. Thanks!
