### ISSUE TITLE
Requesting Updated OTP Support

### ISSUE THREAD

**Issue by antgiant** [belaviyo/keepass-macpass-helper#49]
Since the [KeeOTP plugin](https://bitbucket.org/devinmartin/keeotp/wiki/Home) has gone offline could you please update the OTP support to also be compatible with the additional format the newer and actively supported [KeePassOTP plugin] supports (https://github.com/Rookiestyle/KeePassOTP). (Both are listed on the [official KeePass Plugin page](https://keepass.info/plugins.html#kpotp).)

In particular I would like this to support Google's [otpauth-format](https://github.com/google/google-authenticator/wiki/Key-Uri-Format). (Note: Despite what that notes on that page both Google Authenticator and KeeOTP do support the extra fields including period.)

Thank you

**Comment by belaviyo** [comment]
> In particular I would like this to support Google's otpauth-format

This is doable, but the KeePassOTP uses an integrated db which is not accessible by this extension. The only way for this extension to read an otpauth-formated string is to save it as a normal StringField.

> Stores new OTP secrets in a separate database that can be encrypted using a different masterkey.
This database will be stored within the main database containing the entries as such.
While this increases security by adding a second masterkey for your OTP secrets, it will potentially prevent other ports like KeePass2Android to directly show OTP.

**Comment by antgiant** [comment]
It actually supports both a normal string field and the internal database. When you initially set it up it gives you the choice and tells you to use the string field if integrations are important to you.

**Comment by belaviyo** [comment]
In the normal string field mode, the extension should be able to extract the secret from an otpauth-formated string. I am not sure what the problem is. Do you need the extension to support custom periods?

**Comment by antgiant** [comment]
It doesn't work for me.

I have a normal string field named otp, containing an otpauth-formatted string 
`otpauth://totp/GitHub:github.com/antgiant?secret=***&issuer=GitHub`

When I click OTP (O) I get this error message
> No string-field entry with "otp" key is detected. To generate one-time password tokens, save a new string-field entry with "otp" key and "key=O

**Comment by belaviyo** [comment]
Make sure the "Only return advanced string fields which start with "KPH:" option is unchecked.

<img width="414" alt="Screen Shot 2020-12-16 at 14 45 16" src="https://user-images.githubusercontent.com/1221138/102356390-6d440b00-3fad-11eb-9681-4bd75ba932d9.png">

**Comment by antgiant** [comment]
Well that's embarrassing for me. You are correct that was the my primary issue. Thank you!

However, should I leave this open or create a new ticket for not supporting the the full otpauth-format. In particular I can personally verify that the `period` variable is not currently supported. Any entries with a period different from the default 30 seconds get incorrect codes generated here but correct codes in the Google Authenticator app.

**Comment by belaviyo** [comment]
v0.4.9 will support "period" and "digits" arguments. Thanks for the report.

**Comment by antgiant** [comment]
Great! Thank you!
