### ISSUE TITLE
Not accessible on mobile

### ISSUE THREAD

**Issue by MisterY** [belaviyo/keepass-macpass-helper#5]
It is wonderful that the extension is available for Firefox on Android. This makes it the only browser extension for KeePass that works on mobile browsers.
It is unfortunate then that the activation button is not visible due to the fact that no toolbar buttons are visible in the mobile version of the browser.

Don't know how difficult it would be to implement but I've seen some translation extensions that load translations of the selected into the context submenu.

This, however, might be irrelevant as HTTP  fetching from KeePass is not available on Android.

**Comment by belaviyo** [comment]
> It is unfortunate then that the activation button is not visible due to the fact that no toolbar buttons are visible in the mobile version of the browser.

This extension is based on WebExtension and hence I have no power to force button injection. We need to wait until Firefox supports actionButtons somehow.

> This, however, might be irrelevant as HTTP fetching from KeePass is not available on Android.

True!
