### ISSUE TITLE
Inserting credentials into popups not possible

### ISSUE THREAD

**Issue by BluemediaGER** [belaviyo/keepass-macpass-helper#52]
Hi! First of all, thanks for the helpful extension.

The current version in the Chrome Store seems to be based on the version with the v3 manifest in the repo. With the latest version, credentials can no longer be inserted into popups. The interface cannot be opened there.

In addition, the keyboard shortcut for "Activate the extension" exists twice (see screenshot below), and the second entry doesn't seem to have any function. Are these already known problems?

![image](https://user-images.githubusercontent.com/43730110/132863593-26861093-feb7-4a3a-b938-84d32afe2d18.png)

**Comment by belaviyo** [comment]
Thanks for the report. Both issues should be fixed by 0.6.2 release.
