### ISSUE TITLE
Save New Login = This page has been blocked by [Brave & Edge]

### ISSUE THREAD

**Issue by BitVenturesUSA** [belaviyo/keepass-macpass-helper#53]
Hello, Suddenly when I right click and select "save a new login form" in KeePassHelper, Brave & Edge throws the ascii sad face and "This page has been blocked by [Brave or Edge]" I did some basic investigating and developer tools console shows these issues:

`about:blank:1 Denying load of chrome-extension://jgnfghanfbjmimbdmnjfofnbcgpkbegj/data/save/index.html?url=https%3A%2F%2Fwww.[redacted].com%2F%23state.email.showform. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
VM92:7272 crbug/1173575, non-JS module files deprecated.
(anonymous) @ VM92:7272
`
What's interesting is that if I go to `chrome-extension://jgnfghanfbjmimbdmnjfofnbcgpkbegj/data/save/index.html?url=https%3A%2F%2Fadd0n.com%2Fkeepass-helper.html` directly it loads in a browser page just fine.

**Comment by BitVenturesUSA** [comment]
Just installed the Sept 23rd version and the issue remains.

**Comment by belaviyo** [comment]
The fix is in v0.6.4. Unfortunately, Google took about a week to review this version!
