### ISSUE TITLE
Generates wrong OTP code

### ISSUE THREAD

**Issue by kalahiri** [belaviyo/keepass-macpass-helper#54]
Thanks for your great work and nice plugin. I am very happy with it.

I am trying to use OTP in keepasshelper, but it looks like keepasshelper generates the wrong TOTP code. This is probably an issue of using a different algorithm. Unfortunately, I am not able to figure out how to change the algorithm. 

Setting it up through an TOTP URI didn't work for me, but it is difficult to get it right without some clear instructions on how to implement it.: `...`

**Comment by Swiiney** [comment]
I am using Keepass with keepasshttp and I have the same problem the generated OTP is wrong and not only for gmail but for all my TOTP.
In my database I have an advanced field otp containing key=******
In Keepasshelper  "KPH: " only is unchecked.
I would like to avoid duplicate all the otp fields

**Comment by bastianleicht** [comment]
You probably need to define a different Time Server. That helped for me. Under Advanced Options I had to define the Google 2FA Server for Time Correction (https://www.google.com/generate_204)
![grafik](https://github.com/belaviyo/keepass-macpass-helper/assets/50463419/727d4946-29e4-415f-9880-4809a1e646e5)

**Comment by drok** [comment]
Using the "key=******" syntax generates the wrong (and static) totp for me, but using only the "******" in the value field works correctly.

Also, the secret key cannot include spaces, as it is customary to display key strings.

The extension fails silently on secret keys it cannot parse, and outputs a non-changing/static otp code.

**Comment by belaviyo** [comment]
@drok currently the extension supports value of the following formats:

Value: `otpauth://totp/Example:alice@google.com?secret=*****&issuer=Example`

or 

Value: `*****`

Do you have a sample that inserts secrets in `key=`?

**Comment by drok** [comment]
> Do you have a sample that inserts secrets in `key=`?

@belaviyo, the `key=` sample is in section 13 of the documentation at https://webextension.org/listing/keepass-helper.html
This page is linked as an FAQ from https://chromewebstore.google.com/detail/keepasshelper-password-ma/jgnfghanfbjmimbdmnjfofnbcgpkbegj

**Comment by belaviyo** [comment]
Right, the extension checks both `key=` and `secret=`. But there was a bug that is fixed now. Should work fine from the next release.
