### ISSUE TITLE
Domain name add0n looks like a phishing attack

### ISSUE THREAD

**Issue by rillig** [belaviyo/keepass-macpass-helper#57]
Hi,
When my browser opened the page `https://add0n.com/keepass-helper.html?version=0.6.6&p=0.6.5&type=update` without me having done anything, I immediate went into alert mode.
If you don't want to scare away security-sensitive users, you should probably pick a more straight-forward domain name that doesn't look like a phishing attack.

**Comment by belaviyo** [comment]
Currently, [add0n.com](https://add0n.com/keepass-helper.html) is the official FAQs page of the extension as stated in the stores. Hopefully, the new host will be ready soon, and we can update the homepage URL.
