### ISSUE TITLE
Keyboard shortcut not working on macos anymore

### ISSUE THREAD

**Issue by error401de** [belaviyo/keepass-macpass-helper#58]
I have used Shift + Alt + P as shortcut to activate the addon on my Macs since years. Since the last update it's not working anymore, instead it's typing ∏, which seems to be the default thing for macOS.
Is there any way to get my used shortcut back?

**Comment by belaviyo** [comment]
The extension moved to m3. Please reassign the shortcut; chrome://extensions/shortcuts

**Comment by error401de** [comment]
I just recognised no shortcut I set is working anymore, not only Shift+Alt+P. Can replicate on multiple macOS devices.

**Comment by error401de** [comment]
Just saw it's working in incognito mode, not in the regular one. After a restart of Chrome it's working :D
Was able to reproduce this on all machines as well.

Thanks!

**Comment by belaviyo** [comment]
Maybe the service worker is crashed and hence not responding to the commands. This happens if you have an extension that prevents the new manifest V3 from working correctly.
