### ISSUE TITLE
Automatically popup when I'm on a login page for a site is in my password vault

### ISSUE THREAD

**Issue by carlin-q-scott** [belaviyo/keepass-macpass-helper#6]
I'd like this extension to automatically pop open the password chooser dialog when I visit a login page for a site that's in my keepass password vault. This is the feature I miss the most from KeeFox for Firefox.

**Comment by belaviyo** [comment]
There are other extensions that offer such a feature. But note that the whole idea behind this extension is to keep it as lightweight as possible. For instance this extension does not have any running process in background.

The feature that you request is absolutely doable but here is what needs to be done to achieve this. For each top level navigation, extension needs to send a HTTP request to KeePass application and wait for its response. Then if at least one matching password is detected, it needs to inject a script into the page to check for login forms. If a login form is detected, then background can pass credential info and script can display a dialog.

As you can see this is just too much process for each single page.

In KeePassHelper extension, you just need to focus the login input and press the default keyboard shortcut combination to call the panel.

**Comment by belaviyo** [comment]
So in short, I am not interested to directly add this feature into the add-on as it might not be something that all users need but we can have a separate addon that does the check and then call KeePassHelper either to enter credentials or to open the popup using communication channel.

**Comment by carlin-q-scott** [comment]
I believe KeeFox caches the sites in my vault to provide this functionality since it doesn't notice new sites until I re-open Firefox. That would cut out the back and forth with keepass-http. It could also only match on domain changes to further reduce processing.

I didn't realize there was a shortcut for opening the panel. I'll play with that to see how easy it is to remember and use.
