### ISSUE TITLE
chrome.tabs is undefined

### ISSUE THREAD

**Issue by XIDAGmbH** [belaviyo/keepass-macpass-helper#61]
In Firefox 102.0.1 (64-Bit) when I use the defined keyboard shortcut I get an error.
"chrome.tabs is undefined
Use the options page to connect to KeePass, KeePassXC, or local database"
![Screenshot 2022-07-11 090438](https://user-images.githubusercontent.com/108064824/178207528-d5e0a4f5-4f13-4f88-89e8-2083a1c30e76.jpg)

But it works fine when I click the KeepassHelper Icon on Firefox's top menubar.

**Comment by belaviyo** [comment]
It works fine for me! What is your OS? and why the borders are white! Do you have a custom theme?

**Comment by XIDAGmbH** [comment]
OS: Windows 11.
No custom theme (I checked the firefox settings and it says "system theme - automatic".

Screenrecording of the problem:
https://user-images.githubusercontent.com/108064824/178232965-9120c8a6-6520-4b2a-870a-79c6af49e7d7.mp4

First I use the  icon from the toolbar, then I use the keyboard shortcut.

**Comment by XIDAGmbH** [comment]
You are right, that fixed the problem.
