### ISSUE TITLE
KeePass built-in OTP Secret Issue

### ISSUE THREAD

**Issue by Coool** [belaviyo/keepass-macpass-helper#62]
Hi!

I'm using KeePass [built-in](https://keepass.info/help/base/placeholders.html#otp) OTP Secret [TimeOtp-Secret-Base32](https://github.com/belaviyo/keepass-macpass-helper/blob/3ba2ded94ac90ff2c01a29811efde047702a5c4b/v3/data/cmd/index.js#L25). When press OTP button, returns “[String of HEX type must be in byte increments](https://github.com/belaviyo/keepass-macpass-helper/blob/3ba2ded94ac90ff2c01a29811efde047702a5c4b/v3/connect/jsOTP.js#L305)” error. Can't figure out what's wrong.

Thanks.

**Comment by belaviyo** [comment]
Hi,

What is the format of the string stored in the `TimeOtp-Secret-Base32`? If you can generate a dummy OTP secret that does not work as expected, please share it so I can reproduce the issue.

**Comment by Coool** [comment]
![TimeOtp-Secret-Base32](https://user-images.githubusercontent.com/8421903/182586336-a13152d0-69e4-4bd5-9ce7-0528229abba2.png)
TimeOtp-Secret-Base32 = 3C6OD4JE4T3YRYCZEMD5DGPOMTSQ

**Comment by belaviyo** [comment]
Thanks for the report. It is now fixed. Can you try the developer version to confirm?
https://github.com/belaviyo/keepass-macpass-helper/archive/refs/heads/master.zip -> v3

**Comment by Coool** [comment]
[TOTP.js](https://github.com/belaviyo/keepass-macpass-helper/blob/a2fd6232c1b538d434d509a50029dd0070c5c9c5/v3/data/cmd/index.html#L45) error, complaining could not find. Fix to totp.js or rename TOTP.js to totp.js.
But still have same problem using KPH: otp or TimeOtp-Secret-Base32 returns completely different PIN values than Tray TOTP Plugin. Any clue?

Thanks.

P.S.
Could not load v3 manifest in Waterfox in Develepor mode. Edited existing 0.7.2.2 loaded plugin. 😉

P.S.S.
Why are no new releases found in GitHub Release section?

**Comment by belaviyo** [comment]
I found a bug in the `b32ToHex` conversion. Still, the generated token is different from what KeePass generates. Though, I am not sure which one is correct.

My observation:
Using this secret on https://authy.com's mobile app generates compatible tokens with my extension. Also, `crypto-totp` and `totp-generator` node modules generate the same time-based tokens.
These tokens are different from what KeePass generates. Interestingly, KeePassXC generates different tokens from KeePass and Authy! There is something wrong with this secret, or it is not b32 encoded, or it might not be `RFC4648` variant. Can you provide the "otpauth://totp/..." URL? Would it be possible to generate a new secret and retry?

Please try the latest commit (ff version attached) with some other secrets of yours and see if you can regenerate this issue.

[ff.zip](https://github.com/belaviyo/keepass-macpass-helper/files/9274438/test.zip)

**Comment by Coool** [comment]
If you talk about my provided token above, then it maybe not the which one to rely on. It's one of my existing secret only modified. I don't have any issue so far with your plugin and Tray TOTP Plugin. I don't use regularly KeePass {TIMEOTP} parameter with [Auto-Type](https://keepass.info/help/v2/autotype_obfuscation.html).
You can try `otpauth://totp/Coool:coool@email.com?secret=NMCWBVTA6EVWG3U4DGCT6TLHIKFN3DQF&issuer=Coool&algorithm=SHA1&digits=6&period=30`
I will update you if I have any issue with new release.

Thanks.

**Comment by belaviyo** [comment]
Ok, then, please keep using the `ff.zip` version. If everything works as expected, I'll release this version so that the extension switches to the native crypto lib instead of the old custom lib.

**Comment by Coool** [comment]
Haven't observed any problems. How long do you think to monitor any issue? Week?

**Comment by belaviyo** [comment]
The new version with the updated OTP module is submitted to the stores.

**Comment by Coool** [comment]
belaviyo, great news!
