### ISSUE TITLE
String contains an invalid character

### ISSUE THREAD

**Issue by Coool** [belaviyo/keepass-macpass-helper#64]
I have an issue with some records getting “String contains an invalid character” error when pressing Username, Password or Both, but works fine with Copy Username/Password. Any clue? Could not find such error message in source.

Thanks.

**Comment by belaviyo** [comment]
Is this on Firefox? Can you share an example username with the error? They must contain characters that are not being converted correctly.

**Comment by Coool** [comment]
I'm currently using [Waterfox](https://en.wikipedia.org/wiki/Waterfox). Try lod@inbox.lv username.

**Comment by belaviyo** [comment]
It works for me with this username. Maybe the password is the issue or even string fields.

**Comment by Coool** [comment]
Don't have any clue. Need to observe much longer to figure out why it's happening.

**Comment by Coool** [comment]
Try to use `Habr - Habrahabr (Хабр - Хабрахабр)` in title field of record.

**Comment by belaviyo** [comment]
What is the extension version? It must be fixed by the "0.7.4" release.
https://chrome.google.com/webstore/detail/keepasshelper-password-ma/jgnfghanfbjmimbdmnjfofnbcgpkbegj

**Comment by Coool** [comment]
<img width="742" alt="KeePassHelper_Password_Manager_Invalid_Character_Error" src="https://user-images.githubusercontent.com/8421903/188523879-8dfe0d6e-924a-4f3e-88c2-a2bcab2f1c6b.png">

**Comment by belaviyo** [comment]
Thanks for the report. This was FF-only issue. Should have been fixed by the `0.7.4.1` release.

**Comment by Coool** [comment]
Looks OK with Habr record on 0.7.4.1. Needs more testing to be 100% sure. No commits on new 0.7.4.1 version. What changed?

**Comment by belaviyo** [comment]
This extension runs on manifest v3. There was an issue with my `v3tov2` tool to generate the manifest v2 extension.

https://github.com/belaviyo/v3tov2/commit/f444fa16dcad9a65533de8b10c30e57ad8187f82
