### ISSUE TITLE
OTP: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by mateuszdrab** [belaviyo/keepass-macpass-helper#65]
Hey

Thanks for maintaining the addon.

Just wanted to report an issue getting OTPs in Edge - I get `Cannot read properties of undefined (reading 'filter')`

The otp field starts with `otpauth://totp/......`

Is this a known issue?

**Comment by belaviyo** [comment]
Let's debug. Turn the developer mode on the "chrome://extensions" page. Now open the popup, right-click somewhere inside, and select the "Inspect" item. Switch to the console tab and take a screenshot of the error log.

**Comment by belaviyo** [comment]
@mateuszdrab I think your KeePassHTTP plug-in is not configured to send string fields. right?

**Comment by mateuszdrab** [comment]
That was the case, I enabled the setting and no longer getting an error.
Maybe it would be a good idea to catch that error and provide a more friendly message?

![image](https://user-images.githubusercontent.com/26556541/194700519-7523d7bc-e915-4e7a-9969-7114e346d26d.png)

However, still no OTP is being inserted in a field - there's no error either.

**Comment by belaviyo** [comment]
> However, still no OTP is being inserted in a field - there's no error either.

Do you have the `0.7.5` release?

**Comment by mateuszdrab** [comment]
Nope, `0.7.4`, the version in [Edge store](https://microsoftedge.microsoft.com/addons/detail/keepasshelper-password-ma/bfmglfdehkodoiinbclgoppembjfgjkj)

**Comment by belaviyo** [comment]
I fixed a related bug on `0.7.5`. Try it on Chrome. For Edge, It is still in review.

> However, still no OTP is being inserted in a field - there's no error either.

OTP is copied to the clipboard by pressing the "OTP" button.

**Comment by mateuszdrab** [comment]
I guess we can close this issue.
The only bit of feedback would be maybe to add a feature that fills the OTP in the last active textbox automatically...
Thanks 😉
