### ISSUE TITLE
Not able to inster database.keyx

### ISSUE THREAD

**Issue by Ssri7774** [belaviyo/keepass-macpass-helper#66]
Cannot find a way to insert the .keyx file to access the database from local filesystem.
Using Windows 11, Chrome browser

![image](https://user-images.githubusercontent.com/95307763/194729521-eaa31f1b-f998-4db1-a32d-002e83714d72.png)

![image](https://user-images.githubusercontent.com/95307763/194729522-8c7345ff-a237-4659-afdc-70074508b7de.png)

**Comment by belaviyo** [comment]
There was no support for the key file. As of the next release, you can provide it when using the "Choose File(s)" button. Please give the latest dev version a try.

1. Open "chrome://extensions" in the Chrome browser
2. Turn the developer mode on
3. Drop the "v3" directory in this view

**Comment by mrandrey** [comment]
I tried dropping in the v3 directory and the latest official plugin, but neither allow specifying a key:
<img width="822" alt="Screen Shot 2023-06-30 at 9 42 32 AM" src="https://github.com/belaviyo/keepass-macpass-helper/assets/444565/c52acca0-96a6-4dd1-9c3c-57c73bb0bd01">
