### ISSUE TITLE
Feature request: Add password groups name to main window

### ISSUE THREAD

**Issue by amandrichenko** [belaviyo/keepass-macpass-helper#67]
Sometime you might have lots of passwords related to one domain. In my case I have a couple different projects running on localhost. So I try to sort them using groups. 
For example:
- Project A:
   - Db 1 users:
      - userA
      - userB
   - Db 2 users:
      - userC
      - userD
- Project B:
   - Db 1 users:
      - userE
      
But now when I use extension I only see Title of an entry, so it became:
```
userA
userB
userC
userD
userE
```
and it's not so easy to recognise which one is related to currently opened project. So I really hope it is possible to add name of this group to main window like this for example: ``` userA - Db 1 users - Project A ```

**Comment by belaviyo** [comment]
I added a new column to show the groups. The extension only adds this column if at least one group name is available. It seems like KeePass (KeePassHTTP) does not return groups. KeePassXC returns the child group only. So in your case, it will display "Db 1 users" in a new column.
