### ISSUE TITLE
Confirm a new Key association does not work

### ISSUE THREAD

**Issue by theking2** [belaviyo/keepass-macpass-helper#68]
Clicking the KeePassHelper in Firefox forces a new registration. If I type a new, or existing, Key name and save this in KeePass this seems to to register with KeePassHelper. Clicking again in Firefox on the KeePassHelper icon asks a new confirm with a different key. Clicking on Check in options show "Looks Good"

KeePassHelper does not working in this scenario.
KeePass 2.52 (64-Bit)
KeePassHelpoder 0.7.5
KeePassHttp plugin 1.8.4.2

**Comment by theking2** [comment]
https://user-images.githubusercontent.com/1612152/201166675-29d1dfd8-216b-47b1-a8eb-12e976778383.mp4

**Comment by belaviyo** [comment]
Should have been fixed by the 0.7.6 release. Please reopen if not.
