### ISSUE TITLE
Won't close the Popup Window

### ISSUE THREAD

**Issue by Phelagor** [belaviyo/keepass-macpass-helper#69]
I use Keyboard shortcuts to use the extension in chrome Version 107.0.5304.122 (Official Build) (64-bit). 
ALT+L opens the popup dialog, ALT+K inserts the selected credentials into the form.
This all worked fine before the update of November.

Since the latest Update of the extension whenever I use those shortcuts the popup dialog doesn't disappear. 
The Option for single entry credentials to close the popup is set, but it doesn't change anything, neither when only one entry is found, nor when there are more which I chose one from.

Also in the Background some of the stuff on the website get highlighted (selected), which also haven't happen before.

**Comment by belaviyo** [comment]
> ALT+K inserts the selected credentials into the form.

I am not sure how you configured this one. The popup shortcuts are fixed. 

> Also in the Background some of the stuff on the website get highlighted

It means the extension is not detecting the input element correctly. Please provide a sample page with the issue.

**Comment by Phelagor** [comment]
> I am not sure how you configured this one. The popup shortcuts are fixed.
Oh yeah you are right. I meant ALT+B for both Username & Password autofill.

> It means the extension is not detecting the input element correctly. Please provide a sample page with the issue.
For example it was this site: https://login.aliexpress.com/
I am pretty sure before the Update I never had issues with it.

**Comment by belaviyo** [comment]
> For example it was this site: https://www.paypal.com/signin

`Alt + B` inserts the login for me and closes the popup on Chrome.

**Comment by Phelagor** [comment]
> > For example it was this site: https://www.paypal.com/signin
> 
> `Alt + B` inserts the login for me and closes the popup on Chrome.

Oh I see what to do to replicate.

You have to use keyboard shortcut to open the popup.
As described in my first message, I set ALT+L as a shortcut to open the popup.

It is the key binding for "Open credentials in the embedded mode (useful for popup windows) (does not yet work in Firefox browser)"
(I included a sample Image so hopefully you know which popup I mean)
![keepassHelper-no-form-issue](https://user-images.githubusercontent.com/24415462/204089316-41b3f487-9a96-448a-96bc-8902f819d11b.jpg)

This part is also important for the other issue I opened.

**Comment by belaviyo** [comment]
I see! The problem is with the new modal view of the interface. The `0.7.7` release fixes the issue. Thanks for the report.

BTW, the embedded mode is meant for websites that are opened in a standalone popup window (where there is no access to the action button). You can assign your shortcut to open the interface in the toolbar area instead to prevent possible incompatibilities.
