### ISSUE TITLE
Options to specify host and port to connect

### ISSUE THREAD

**Issue by Endag** [belaviyo/keepass-macpass-helper#7]
Title says it - sometimes it needed to change at least port for connection to KeePassHttp because default may be used by another application.

And ability to connect to remote host will be neat to just because KeePassHttp supports it.

**Comment by belaviyo** [comment]
Thanks for the suggestion. I added a new setting in the options page to allow users to modify both values. Please give it a try and let me know if it works as expected or not.

https://github.com/belaviyo/keepass-macpass-helper/archive/master.zip
https://stackoverflow.com/questions/24577024/install-chrome-extension-not-in-the-store
