### ISSUE TITLE
Not finding form for credentials on sites anymore

### ISSUE THREAD

**Issue by Phelagor** [belaviyo/keepass-macpass-helper#70]
Also another Issue I have since the November update of the extension, using chrome Version 107.0.5304.122 (Official Build) (64-bit), is that it doesn't sometimes can't find the forms to fill.
It worked on those sites before and usually was pretty good in this. 
But now I have a lot of sites it was working before where the extension just says "No active form found! Focus an element on the page and retry."

**Comment by belaviyo** [comment]
Please provide a sample page with the issue. Can you try the extension on a clean profile too?
https://support.google.com/chrome/answer/2364824?hl=en&co=GENIE.Platform%3DDesktop

**Comment by Phelagor** [comment]
So as mentioned in the other post, I removed the extension from my all-day browser for now.
For test purpose I just installed it on my second browser (Chrome Version 108.0.5359.48 (Official Build) beta (64-bit)) on a different profile. Also there are no other extensions active on that browser.

For the here described problem a sample page would be:
https://login.aliexpress.com/

**Comment by belaviyo** [comment]
> https://login.aliexpress.com/

It seems they have recently updated this page. There is no login form on it anymore! I just pushed a fix with this particular login page. If you have another example, please share.
