### ISSUE TITLE
Impossible to close the panel with escape if not in focus

### ISSUE THREAD

**Issue by gagarine** [belaviyo/keepass-macpass-helper#8]
When we open the panel, it's not in focus. Pressing "esc" do not close it. Clicking in the panel and the press "esc" close it.

![screen shot 2017-08-12 at 12 10 48](https://user-images.githubusercontent.com/164074/29239813-64e3bce0-7f57-11e7-8ac5-55cc856bc56d.png)

Tested on Firefox nightly 57a on macos.

**Comment by belaviyo** [comment]
Will be fixed on 0.2.5
